name: Install Nginx on Self-Hosted macOS Runner

on:
  push:
    branches: [ main ]

jobs:
  install-nginx:
    runs-on: self-hosted  # Your macOS self-hosted runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update Homebrew and Install Nginx
      run: |
        brew update
        brew install nginx

    - name: Start Nginx using Homebrew services
      run: |
        brew services start nginx

    - name: Check Nginx Process
      run: |
        ps aux | grep nginx

    - name: Test Nginx is Running
      run: |
        curl -I http://localhost
